### ISSUE TITLE
Create a project in Projects section

### ISSUE THREAD

**Issue by smddzcy** [bounswe/bounswe2017group3#13]
# About
GitHub offers a great board for project management, just like Trello, and we should set up one for future use.

# TODO
- [x] Create a project in Projects in section.
- [x] Create appropriate columns in the created project board.

**Comment by smddzcy** [comment]
@gokceuludogan Can you review the board I've created and close the issue if it's OK?

**Comment by gokceuludogan** [comment]
That's fine.
