### ISSUE TITLE
Choosing a mockup tool

### ISSUE THREAD

**Issue by smddzcy** [bounswe/bounswe2017group3#17]
# About

As we've discussed in the class, we should choose a mockup tool to build a mockup (a basic interface of our *desired* product).

**Comment by smddzcy** [comment]
@bounswe/bounswe2017group3 I'll share the tools I've used and liked in the past, but it'd be better if we all share our thoughts and recommendations.

**Comment by MertKalaylioglu** [comment]
I used Balsemiq Mock-Up before but NinjaMock seems good.

**Comment by smddzcy** [comment]
I've used [Marvel](https://marvelapp.com/) and [Invision](https://www.invisionapp.com/), and both of them are really good. We should discuss it on our nearest meeting and choose one to create a quick mockup 🚀

**Comment by gokceuludogan** [comment]
I have taken a look at all of them. Both Balsemiq and NinjaMock seem easier to me but I think NinjaMock looks nicer.

**Comment by smddzcy** [comment]
Since we've agreed on Balsamiq (and created an initial mockup) I'm closing this 👍 We can always change the tool whenever it doesn't suit our needs.
