### ISSUE TITLE
Create a simple mockup for the project

### ISSUE THREAD

**Issue by smddzcy** [bounswe/bounswe2017group3#26]
# About

We should create a mockup for our project. We can track the changes of our mockup on this issue.

# Visuals

Here are the visuals of our initial mockup.

Main Page - Guest
![main page - guest](https://cloud.githubusercontent.com/assets/13895224/23330370/43bc14a0-fb5d-11e6-814f-bae5cde92d9b.png)

Sign In Page
![sign in](https://cloud.githubusercontent.com/assets/13895224/23330375/5404575a-fb5d-11e6-8af4-1989644c8bb0.png)

Main Page - User
![main page - user](https://cloud.githubusercontent.com/assets/13895224/23330373/4bdd1fda-fb5d-11e6-8d83-5997622910fe.png)

Create Event Page
![create event](https://cloud.githubusercontent.com/assets/13895224/23330377/6a58d42c-fb5d-11e6-80b5-c699f43f48c1.png)

Create Group Page
![create group](https://cloud.githubusercontent.com/assets/13895224/23330378/77019650-fb5d-11e6-8e2f-8a84b55e74b8.png)

Group Page
![group page](https://cloud.githubusercontent.com/assets/13895224/23330380/7bb45cf0-fb5d-11e6-9fef-208295de4724.png)

Annotation Example
![group page copy](https://cloud.githubusercontent.com/assets/13895224/23330381/800a1cb8-fb5d-11e6-8fb5-c25d8d1879b4.png)

---

Link to the mockup file: https://trello-attachments.s3.amazonaws.com/58ab5afd86df9b2d18462cee/58b15b2f24aef08813006e20/b871e14135793711587b877670b46d2e/initial-mockup.bmpr

**Comment by OnurOrhan** [comment]
* Search Page

![image](https://cloud.githubusercontent.com/assets/25687182/23377286/8150bed0-fd40-11e6-8786-5a04d54cdae3.png)

* Group Page

![image](https://cloud.githubusercontent.com/assets/25687182/23377274/72eb5f80-fd40-11e6-9d09-54e610fa5964.png)

**Comment by esra-aydemir** [comment]
These are some other pages of mobile version:

![sign up](https://cloud.githubusercontent.com/assets/9717121/23385296/c6e49f40-fd57-11e6-8609-b9b9d4126441.png)

![log in](https://cloud.githubusercontent.com/assets/9717121/23385301/cc925cc0-fd57-11e6-8667-8aa963511cc1.png)

![user - homepage](https://cloud.githubusercontent.com/assets/9717121/23385308/d7682670-fd57-11e6-9fab-f6a4a58f3fd2.png)

![guest - homepage](https://cloud.githubusercontent.com/assets/9717121/23385316/da8cb2f8-fd57-11e6-8181-2baf1a1a96c1.png)

![create event page](https://cloud.githubusercontent.com/assets/9717121/23385324/e633d71c-fd57-11e6-941d-451f6c98b718.png)

![create group page](https://cloud.githubusercontent.com/assets/9717121/23385328/e91cc9de-fd57-11e6-8342-bdd9e0f3db99.png)

![group page](https://cloud.githubusercontent.com/assets/9717121/23385334/f1304d30-fd57-11e6-93fd-e81ba0b1a8b9.png)

![annotation example](https://cloud.githubusercontent.com/assets/9717121/23385346/fd0dfdb4-fd57-11e6-98cd-eee5e2ddf446.png)


![moderator page](https://cloud.githubusercontent.com/assets/9717121/23385343/f8f12ba2-fd57-11e6-87e5-07106a6d9e62.png)

**Comment by smddzcy** [comment]
Here is the updated mockup after the feedback in the class: https://transfer.sh/12Ud9R/web-mockup.bmpr

![main page - guest](https://cloud.githubusercontent.com/assets/13895224/23399748/71a9e0b6-fdb2-11e6-9f4d-eefedb048d4e.png)
![sign up](https://cloud.githubusercontent.com/assets/13895224/23399752/71c490c8-fdb2-11e6-859c-19aa3337b969.png)
![main page - user](https://cloud.githubusercontent.com/assets/13895224/23399751/71ad7c3a-fdb2-11e6-9b4c-341670867d31.png)
![create event](https://cloud.githubusercontent.com/assets/13895224/23399746/71a7a206-fdb2-11e6-8bb0-0ca87a32b4ba.png)
![create group](https://cloud.githubusercontent.com/assets/13895224/23399749/71ac36ea-fdb2-11e6-8bf5-2be68da1c4b6.png)
![group page - annotation](https://cloud.githubusercontent.com/assets/13895224/23399750/71acec52-fdb2-11e6-923d-e1f89351a6e3.png)
![group page](https://cloud.githubusercontent.com/assets/13895224/23399747/71a7b37c-fdb2-11e6-8472-5381fd1ec663.png)

**Comment by smddzcy** [comment]
Edited 2 pages of web mockup:

|Main Page - Guest|Main Page - User|
|--|--|
|![main page - guest](https://cloud.githubusercontent.com/assets/13895224/23517359/ca7d5ed0-ff78-11e6-8d6c-7f6c46abba1c.png)|![main page - user](https://cloud.githubusercontent.com/assets/13895224/23517360/caa0e558-ff78-11e6-9591-77c8a25561c8.png)|

**Comment by OnurOrhan** [comment]
![groups](https://cloud.githubusercontent.com/assets/25687182/23525624/28bc4fac-ffa0-11e6-8e74-73b04db707cb.png)
![search page](https://cloud.githubusercontent.com/assets/25687182/23524225/baea3d18-ff9a-11e6-9a0b-bc686293c7c0.png)
![group page 1](https://cloud.githubusercontent.com/assets/25687182/23525085/48a77370-ff9e-11e6-8883-0b1592291877.png)

**Comment by smddzcy** [comment]
I'm closing this issue since we've created a simple mockup and achieved what this issue is about 😄 We can continue on web/mobile specific enhancement issues.
