### ISSUE TITLE
Create a use case diagram

### ISSUE THREAD

**Issue by gokceuludogan** [bounswe/bounswe2017group3#28]
# ABOUT

Since we are supposed to create a use case diagram, after the meeting 4 I have created below diagram based on the topics we have talked. Here we can track changes we will make on it 
![image](https://cloud.githubusercontent.com/assets/9639399/23497302/800868da-ff33-11e6-8538-bf3770ea7ccc.png)

**Comment by smddzcy** [comment]
@gokceuludogan To prevent duplicate issues: Should we continue on #30, or should I delete that issue? I suggest we name this issue _"Create a use case diagram"_ and continue on the new one to divide tasks into smaller issues.

**Comment by gokceuludogan** [comment]
Ok. Since we will continue on the new one, I am closing this issue.
