### ISSUE TITLE
UML Generalization

### ISSUE THREAD

**Issue by esra-aydemir** [bounswe/bounswe2017group3#29]
We have inspected the uml file and editted. There should be generalization between user and moderator and include arrows coming to moderator should be deleted. 
We could not find how to add generalization.

This is the link of new uml. it can be loaded to wiki after adding generalization
**Add following user to use case diagram
http://yuml.me/edit/afe755c6

**Comment by esra-aydemir** [comment]
Will/Should annotations and tags be added to use case diagram?

**Comment by gokceuludogan** [comment]
I think tagging must be added but I am not sure about the annotations.

**Comment by MertKalaylioglu** [comment]
Generalization is added.
https://yuml.me/edit/7b73cdac

**Comment by smddzcy** [comment]
@esra-aydemir I think both should be added since they are actual _use cases_.
@MertKalaylioglu Looks great 🚀

**Comment by smddzcy** [comment]
I'm closing this one 👍
