### ISSUE TITLE
Complete lacking mock-up pages

### ISSUE THREAD

**Issue by esra-aydemir** [bounswe/bounswe2017group3#32]
- [x] forum page
- [x] viewing other users profile page  (add follow button)
- [x] Profile (add following a user, a group choices?)
- [x] group page (add follow unfollow join buttons -show 'following' info-)
- [x] group page (if member -> a text box to add content -> a share button)
- [x] group page(add leave group etc options on use case diagram)
- [x] Follows (add links to follows from profile & homepage)
- [x] Detail search page (person search, group search)
- [x] group create page (add choose theme dropdown)
- [x] search page (add dropdown for searc by group-event-tag option)
- [x] create content page (lınked by the create button on user-maın page)

**Comment by smddzcy** [comment]
I've added the mockups for following a group, but I need some clarification for the others. @esra-aydemir Help me in Slack whenever you are available 🤓

**Comment by smddzcy** [comment]
Mockups are done 👌  I've created the profile pages, group options (leave, follow, manage etc.), and create content page. I've also made some changes like adding icons to buttons, changing some colors, adding some action pages.

I'm sending the new web mockups to you on Slack (also attaching here). I'll change the wiki page tomorrow 🚀 

[web-mockup.6.3.2017.zip](https://github.com/bounswe/bounswe2017group3/files/819913/web-mockup.6.3.2017.zip)

**Comment by smddzcy** [comment]
I've updated the mockups - added links to profile pages, changed _Lorem ipsum_ with a realistic text: [web-mockup.6.3.2017.rev2.zip](https://github.com/bounswe/bounswe2017group3/files/820485/web-mockup.6.3.2017.rev2.zip)

**Comment by smddzcy** [comment]
Added mockups for adding a user and accepting pending join requests for moderators: [web-mockup.6.3.17.rev3.zip](https://github.com/bounswe/bounswe2017group3/files/821131/web-mockup.6.3.17.rev3.zip)

**Comment by buraktomruk** [comment]
Adding some missing mockups for mobile
[mobile_mockup.bmpr.zip](https://github.com/bounswe/bounswe2017group3/files/822550/mobile_mockup.bmpr.zip)

**Comment by OnurOrhan** [comment]
![image](https://cloud.githubusercontent.com/assets/25687182/23643934/e04f8396-0315-11e7-94ca-43a12b927606.png)
![image](https://cloud.githubusercontent.com/assets/25687182/23643939/e496a7f4-0315-11e7-86d2-cafae62d80b9.png)
![image](https://cloud.githubusercontent.com/assets/25687182/23643944/e898600e-0315-11e7-8f95-6df42b907bd4.png)
![image](https://cloud.githubusercontent.com/assets/25687182/23643958/f160ead0-0315-11e7-8a6f-4e524aa20e3c.png)
![image](https://cloud.githubusercontent.com/assets/25687182/23643964/f5460f04-0315-11e7-9571-51e717e77031.png)
![image](https://cloud.githubusercontent.com/assets/25687182/23643978/014ba1ce-0316-11e7-937f-8b6b2a534c52.png)
![image](https://cloud.githubusercontent.com/assets/25687182/23643984/04b1d57c-0316-11e7-8b5e-a73c8e91e77f.png)
![image](https://cloud.githubusercontent.com/assets/25687182/23643990/08fcf21a-0316-11e7-8f5a-4f81906db619.png)
![image](https://cloud.githubusercontent.com/assets/25687182/23643995/0ea86ec4-0316-11e7-99b2-4e8963829b05.png)
![image](https://cloud.githubusercontent.com/assets/25687182/23643997/11e1c8a6-0316-11e7-8ceb-01df68a5b31f.png)
![image](https://cloud.githubusercontent.com/assets/25687182/23644000/1914b692-0316-11e7-816d-a4790a121f5a.png)
![image](https://cloud.githubusercontent.com/assets/25687182/23644005/1beeafee-0316-11e7-9672-3cfd8f55d5f2.png)
![image](https://cloud.githubusercontent.com/assets/25687182/23644017/2a8b76d6-0316-11e7-8598-b7ef1be4432c.png)
![image](https://cloud.githubusercontent.com/assets/25687182/23644020/2d5d1aae-0316-11e7-9b38-f3265c394a60.png)
![image](https://cloud.githubusercontent.com/assets/25687182/23644024/316868b0-0316-11e7-8113-92b0eb0cb7c1.png)

**Comment by OnurOrhan** [comment]
Hatice Esra:

![image](https://cloud.githubusercontent.com/assets/25687182/23644066/672fdb22-0316-11e7-98ce-2795f7180978.png)
![image](https://cloud.githubusercontent.com/assets/25687182/23644069/6a7391ca-0316-11e7-81b2-36f0438a2c36.png)
![image](https://cloud.githubusercontent.com/assets/25687182/23644071/6d962642-0316-11e7-9c0c-e5142505c5d7.png)
![image](https://cloud.githubusercontent.com/assets/25687182/23644077/7020f810-0316-11e7-9491-746fbf42d3d0.png)
![image](https://cloud.githubusercontent.com/assets/25687182/23644078/7356d1b2-0316-11e7-890d-31edbb1f5122.png)
![image](https://cloud.githubusercontent.com/assets/25687182/23644083/7659626c-0316-11e7-8895-0d063c3a7ebd.png)
![image](https://cloud.githubusercontent.com/assets/25687182/23644085/7970718e-0316-11e7-820a-4c826096a0af.png)
![image](https://cloud.githubusercontent.com/assets/25687182/23644087/7ca9fa64-0316-11e7-9d66-f3f06a0dc0c0.png)
![image](https://cloud.githubusercontent.com/assets/25687182/23644094/8082a41a-0316-11e7-950c-87646a68eec6.png)
![image](https://cloud.githubusercontent.com/assets/25687182/23644096/84094620-0316-11e7-858e-f16e967369ed.png)
![image](https://cloud.githubusercontent.com/assets/25687182/23644097/876d5f18-0316-11e7-9f34-b8023737cef2.png)
![image](https://cloud.githubusercontent.com/assets/25687182/23644098/8a68b3de-0316-11e7-960b-0501f8e2d866.png)
![image](https://cloud.githubusercontent.com/assets/25687182/23644100/8dc8ad4a-0316-11e7-8de3-34b04fe703d3.png)
![image](https://cloud.githubusercontent.com/assets/25687182/23644104/90ed20d2-0316-11e7-92af-5638df9b2c54.png)
![image](https://cloud.githubusercontent.com/assets/25687182/23644112/95d3639a-0316-11e7-812b-7fdeb78323ec.png)
