### ISSUE TITLE
Create scenarios by using our use cases

### ISSUE THREAD

**Issue by smddzcy** [bounswe/bounswe2017group3#36]
# About

Our mockup structure (a flow of mockups) is not descriptive enough at the moment. We should create scenarios by using our use cases and after that create mockups for each of those scenarios.

## TODO

- [x] Create scenarios by using our use cases.
Examples:
- https://github.com/bounswe/bounswe2015group3/wiki/Scenarios
- https://github.com/bounswe/bounswe2015group4/wiki/Scenarios
- [x] Create a wiki page for the scenarios.

**Comment by gokceuludogan** [comment]
I have created a wiki page for the scenarios and added two scenarios about searching and joining a group and searchin by tag and joining an event.

**Comment by smddzcy** [comment]
Our scenarios look pretty cool. I've fixed the typos and added a better text for Scenario 6. I'm closing this one 👌
