### ISSUE TITLE
Tasks after meeting on 8th of March

### ISSUE THREAD

**Issue by gokceuludogan** [bounswe/bounswe2017group3#38]
- [x] Review and add use case scenarios @memhak 
- [x] Create a template for the class diagram @gokceuludogan @esra-aydemir 
- [x] Review use cases and use case diagram @ugurcanarikan

**Comment by memhak** [comment]
I've reviewed the existing use case scenarios and added some.

**Comment by gokceuludogan** [comment]
Could you add also the tag and annotation part to use case diagram? @ugurcanarikan

**Comment by smddzcy** [comment]
Class diagram is ready for review, so every todo is done. I'm closing this 👌

**Comment by gokceuludogan** [comment]
The tag and the annotation part was missing in the use case diagram. I have added them. Here it is:
![usecasediagram](https://cloud.githubusercontent.com/assets/9639399/23895039/0966e728-08ad-11e7-8aea-0e4ea049fc7a.png)
