### ISSUE TITLE
Create a class diagram

### ISSUE THREAD

**Issue by gokceuludogan** [bounswe/bounswe2017group3#40]
## About

Since we are going to make a class diagram, I have opened a document and started to create the diagram in lucidchart. 

## To-do

- [x] Create a class diagram.

**Comment by gokceuludogan** [comment]
Here is a useful tutorial about uml and class diagram: 
https://www.ibm.com/developerworks/rational/library/content/RationalEdge/sep04/bell/

**Comment by smddzcy** [comment]
Here is the initial diagram:
![class diagram - page 1](https://cloud.githubusercontent.com/assets/13895224/23817434/c594822a-05fb-11e7-8be0-6308caba7bf5.png)

We should add the annotations to the diagram (there is a small class for that but it's not complete yet 😅) and add some more declarations about how classes interact, but it looks OK for now. Please review 👍

**Comment by gokceuludogan** [comment]
I have reviewed it. It's OK for now.
