### ISSUE TITLE
Create the login sequence diagram

### ISSUE THREAD

**Issue by smddzcy** [bounswe/bounswe2017group3#41]
## About

* **Related Issues:** https://github.com/bounswe/bounswe2017group3/issues/30
* **Other Related Links:** https://github.com/bounswe/bounswe2015group3/wiki/Sequence%20Diagrams (Sequence diagram example - 2015 group 3)

We should create the UML sequence diagrams as it's told in our last assignment. As my part, I'll take the login sequence diagram.

## Visuals

An example from internet:
![](http://agilemodeling.com/images/models/sequenceDiagramEnrollInSeminar.jpg)

**Comment by smddzcy** [comment]
I've created the login sequence:
![login sequence](https://cloud.githubusercontent.com/assets/13895224/23866556/dc875e8a-0821-11e7-846f-cf088eba4b30.png)

We can use [websequencediagrams.com](websequencediagrams.com) to generate sequence diagrams. Here's the code for mine:
```
title Login Sequence

User->User Interface: fill login information
User->User Interface: click on login button
User Interface->User Interface: check if input is valid

alt valid input
    User Interface->Backend API: authenticate user
    Backend API->Database: check login information
    
    alt user exists
        Database->Backend API: success
        Backend API->User Interface: user is authenticated
        User Interface->User: redirect to main page
    else user doesn't exist
        Database->Backend API: fail
        Backend API->User Interface: user is not authenticated
        User Interface->User: show error message
    end
else invalid input
    User Interface->User: show error message
end
```

**Comment by smddzcy** [comment]
I think it's not totally correct. I'll add the life cycles and use the classes in our class diagram instead of abstract objects 👌

**Comment by smddzcy** [comment]
Since our class diagram is actually the diagram of our backend API, the user interface here is not a class. It can be our web interface, Android application or iOS application. It will send a request to our backend API and the classes there will take care of the rest.

Here is the final login sequence diagram:
![login sequence](https://cloud.githubusercontent.com/assets/13895224/23871629/e8a76bc6-0833-11e7-9f08-330ade017ec8.png)

**Comment by smddzcy** [comment]
I'll add it to the wiki page after the review, if it's OK.

**Comment by memhak** [comment]
I think is a good diagram.

**Comment by smddzcy** [comment]
I've updated the diagram after the class this morning:
![login sequence](https://cloud.githubusercontent.com/assets/13895224/23899636/a11a76d2-08be-11e7-9ff3-1ee672a45817.png)

**Comment by smddzcy** [comment]
I'm closing this one since it's reviewed 👍
