### ISSUE TITLE
Create add tag sequence diagram 

### ISSUE THREAD

**Issue by memhak** [bounswe/bounswe2017group3#42]
## About

* **Related Issues:** #41 

Our task is creating sequence diagrams, as my part I will create one for adding tags.

## To-do

- [ ] Create the sequence diagram @memhak

**Comment by memhak** [comment]
[This ](https://www.websequencediagrams.com/cgi-bin/cdraw?lz=dGl0bGUgQWRkaW5nIFRhZyBTZXF1ZW5jZQoKVXNlci0-VXNlciBJbnRlcmZhY2U6IGNsaWNrIG9uIHRoZSAiYWRkIHRhZyIgYnV0dG9uAC8FACQKLT5TeXN0ZW06IGNhbkFkZFRhZyh0YXJnZXQ6VGFnZ2FibGUpCgAdBgAgC2hlY2sgaWYgdXNlciBpcyBwZXJtaXR0ZWQKCmFsdAARBmhhABEHc3Npb24KICAgIABACACBIRAAGBgAgRsQVXNlcgAnB2lzIHJlZGlyZWN0ZWQgdG8AgV0Ld2luZG93ADgJAFgXYWRkcyB0YWcgAFUVAIINCGEAggoIZzpUYWcpAIEpHXN1Y2Nlc3MAgR8bdGFnIGlzIGFkZGVkCmVsc2UAgjsGZG9lc24ndCBoYXZlAIIGLQAdHACCJhZzaG93IGVycm9yIG1lc3NhZ2U&s=napkin)is the first draft. I will add it after review.

**Comment by smddzcy** [comment]
Here is my review:

1. `Activate Permission` is a bit ambiguous. You can check if the user has permission like this:

Use `System`'s `getUserById(id: UUID)` method, which gives you a `User` instance. Then get the `Permission` instance of the user by using `getPermission()` method on the `User` instance. Then you can check with that permission instance if the user has permission or not.

In a programmatic syntax:
  ```java
  User user = System.getUserById("xxxxxxxx-xxxx-Mxxx-Nxxx-xxxxxxxxxxxx");
  Permission permission = user.getPermission();
  // insert a Taggable instance here, for ex. an Event instance.
  // You can get the instance from System class using its id. Assume you get the id from user interface.
  if (permission.canAddTag(instance)) {
    // User has permission.
    ...
  } else {
    // User doesn't have permission.
    ...
  }
  ```

2. On the `addTag(tag: Tag)` part, I think you should show the creation of the `Tag` object in UML terms. Take a look at this StackOverflow post if you don't know how to show object instantiation: http://stackoverflow.com/questions/2127875/how-do-you-show-instantiation-in-a-uml-sequence-diagram

> Create message on a sequence diagram http://i.msdn.microsoft.com/Dd409377.UML_Sequence(en-us,VS.100).png
  UML Sequence Diagrams: Reference at http://msdn.microsoft.com/en-us/library/dd409377%28VS.100%29.aspx

I'm not an expert on this (which means you should take at least one more review 🚎 ) but it looks very good other than these 2 missing details 👌

**Comment by memhak** [comment]
I updated the draft after the reviews 

![new](https://www.websequencediagrams.com/cgi-bin/cdraw?lz=dGl0bGUgQWRkaW5nIFRhZyBTZXF1ZW5jZQoKVXNlci0-K1VzZXIgSW50ZXJmYWNlOiBjbGljayBvbiB0aGUgImFkZCB0YWciIGJ1dHRvbgAwBQAkCi0-InN5c3RlbTogUwADBSI6IGNhbkFkZFRhZyh0YXJnZXQ6VGFnZ2FibGUpCgAdEC0-KwAuEmdldFVzZXJCeUlEKGlkOiBVVUlEABQnY3JlYXRlIABpCABdEwCBER4AgSIGOgA4CSkgAB0maGVjayBpZiB1c2VyIGlzIHBlcm1pdHRlZAoKYWx0ABEGaGEAEQdzc2lvbgogICAgAIF9EgCCfBAAECoAgXEcAGgFAIMpEFVzZXIAWgdpcyByZWRpcmVjdGVkIHRvAINrC3dpbmRvdwA4CQCBCxdhZGRzIHRhZyAAVRUAg1ETYQCCaQk6VGFnKQCBZycAgS0ldGFnIGlzIGFkZGVkCmVsc2UAgxAGZG9lc24ndCBoYXZlAIJRNwAnHACCSBZzaG93IGVycm9yIG1lc3NhZ2U&s=default)

**Comment by smddzcy** [comment]
Oh, I forgot: I think you need a layer of a Taggable class here, for instance: a `Group` or `Event`. Because user interface should call `addTag` method on that and that class will take care of the permissions.

Also the object instantiation is still not there 😅  You need a `<<create>>` call on the `Tag` class like this:
![screen shot 2017-03-14 at 01 09 38](https://cloud.githubusercontent.com/assets/13895224/23877342/8ad6b9fe-084a-11e7-91ee-a5dbb773e7d3.png)

**Comment by smddzcy** [comment]
@memhak I'm making this `in progress` since everything is changed 😄  Please take a look the service classes and my sequence diagram for an example.

**Comment by memhak** [comment]
okay, I will make the changes 👍

**Comment by gokceuludogan** [comment]
@memhak Since we should review the diagram, could you please update it as soon as possible?

**Comment by memhak** [comment]
This is the new draft, now it has some flows. I'm gonna improve the lifespans, but please share your reviews. :)

![draft](https://www.websequencediagrams.com/cgi-bin/cdraw?lz=dGl0bGUgQWRkaW5nIFRhZyBTZXF1ZW5jZQoKVXNlci0-QWN0aXZpdHkgU2VydmljZTogYWRkVGFnKGEAEgdJRDogVVVJRCx0YWdwcm9wczpNYXA8U3RyaW5nLCBPYmplY3Q-KTpUYWcKADwQLT5Vc2VyOiBjaGVjayBpZiB1c2VyIGhhcyBwZXJtaXNzaW9uCgoKYWx0AAUVICAgIACBDRgAGBgAaxgAdQVpcyByZWRpcmVjdGVkIHRvICJhZGQgdGFnIiB3aW5kb3cAaAsrAIIHEmNyZWF0ZSB0YWcAeSJhZGRzIHRhZyAAgH8XInN5c3RlbTogUwADBSI6ACgFaXMgYWRkZWQKZWxzZQCCKAZkb2Vzbid0IGhhdmUAgXUoABgiAIMSGHNob3cgZXJyb3IgbWVzc2FnZQ&s=default)

**Comment by gokceuludogan** [comment]
@memhak We have removed the system and added services for its methods. Please check the class diagram on #49 and update the diagram. Also we should show the interaction with database. You can take a look at the the last versions of login, create group and event diagrams.

**Comment by memhak** [comment]
new one 

![new](https://www.websequencediagrams.com/cgi-bin/cdraw?lz=dGl0bGUgQWRkaW5nIFRhZyBTZXF1ZW5jZQoKVXNlci0-K0FjdGl2aXR5IFNlcnZpY2U6IGFkZFRhZyhhABIHSUQ6IFVVSUQsdGFncHJvcHM6TWFwPFN0cmluZywgT2JqZWN0Pik6VGFnCgA8EC0-AEwSY2hlY2sgaWYgdXNlciBoYXMgcGVybWlzc2lvbgoKCmFsdAAFFSAgICAAThEtPlRhZzogPDxjcmVhdGU-PgARFj4rRGF0YWJhc2U6IAAkBiB0YWcgcmVjb3JkAFUFABgILS0-LQCBfxJzdWNjZXNzAGwYVXNlcgAbCmVsc2UAgVYGZG9lc24ndCBoYXZlAIEoIy0AQQdob3cgZXJyb3IgbWVzc2FnZQoKCg&s=default)

**Comment by smddzcy** [comment]
@memhak Looks good, closing 👍
