### ISSUE TITLE
Creating Content Sequence Diagram

### ISSUE THREAD

**Issue by OnurOrhan** [bounswe/bounswe2017group3#44]
Create a "Creating Content Sequence Diagram", corresponding to Use Case #6

**Comment by OnurOrhan** [comment]
![content creation sequence](https://cloud.githubusercontent.com/assets/25687182/23875554/efbc3f74-084a-11e7-89da-86134a7de782.png)

**Comment by smddzcy** [comment]
I have some reviews:

1. `Activate Permission` is a bit ambiguous. You can check if the user has permission like this:

Use `System`'s `getUserById(id: UUID)` method, which gives you a `User` instance. Then get the `Permission` instance of the user by using `getPermission()` method on the `User` instance. Then you can check with that permission instance if the user has permission or not.

In a programmatic syntax:
  ```java
  User user = System.getUserById("xxxxxxxx-xxxx-Mxxx-Nxxx-xxxxxxxxxxxx");
  Permission permission = user.getPermission();
  // insert a CanAccess instance here, for ex. a Group instance.
  // You can get the instance from System class using its id. Assume you get the id from user interface.
  if (permission.canAccess(instance)) {
    // User has permission.
    ...
  } else {
    // User doesn't have permission.
    ...
  }
  ```

2. `Check if member of the group` is also ambiguous. You can make it specific like this:

Assume you have the group ID (which will come from the user interface in the real world). Use `System`'s `getGroupById(id: UUID)` method, which gives you a `Group` instance. Then get the members of the group by using `getMemberList()` on the group instance, and check if the user is in it or not.

In a programmatic syntax:
```
// Assume you get the user id from user interface.
User user = System.getUserById("xxxxxxxx-xxxx-Mxxx-Nxxx-xxxxxxxxxxxx");
Group group = System.getGroupById("xxxxxxxx-xxxx-Mxxx-Nxxx-xxxxxxxxxxxx");
List<User> members = group.getMemberList();

if (members.contains(user)) {
// User is a member.
...
} else {
// User is not a member.
...
}
```
3. On the `createPost(post: Post)` part, I think you should show the creation of the `Post` object in UML terms. Take a look at this StackOverflow post if you don't know how to show object instantiation: http://stackoverflow.com/questions/2127875/how-do-you-show-instantiation-in-a-uml-sequence-diagram

> Create message on a sequence diagram http://i.msdn.microsoft.com/Dd409377.UML_Sequence(en-us,VS.100).png
  UML Sequence Diagrams: Reference at http://msdn.microsoft.com/en-us/library/dd409377%28VS.100%29.aspx

4. I think by `Direct` you meant `Redirect`.

5. Can you change the sketch style to the first style (most basic one, which we use) by clicking the `Styles` button in the right upper part of the website ([websequencediagrams.com](websequencediagrams.com))?

**Comment by smddzcy** [comment]
@OnurOrhan We should update this diagram according to our new class diagram. You can take a look login, create event or create group sequence diagrams.

**Comment by gokceuludogan** [comment]
@OnurOrhan  Can you update this diagram soon so that we have enough time to review it?

**Comment by OnurOrhan** [comment]
Of course my friend! You could check this version. @gokceuludogan 
![content creation sequence 2](https://cloud.githubusercontent.com/assets/25687182/24118860/5a22b2c4-0dc0-11e7-8360-6cd3f89972ae.png)

**Comment by gokceuludogan** [comment]
@OnurOrhan Please check the class diagram on #49. We have updated it and divided the system class as service classes. Additionally you should show the interactions with the database. Taking a look at the new version of login, create group and event diagrams might also be useful.

**Comment by smddzcy** [comment]
This is the only sequence diagram we couldn't finish. @OnurOrhan Although it's technically good, you should use the service classes and simplify it a bit 😄 Please take a look at @gokceuludogan's examples.

**Comment by smddzcy** [comment]
@OnurOrhan We've talked about this issue in the meeting today and set the deadline as **28.03.17 11.59 pm** 👍

**Comment by OnurOrhan** [comment]
![content creation sequence 4](https://cloud.githubusercontent.com/assets/25687182/24631938/fb505a7e-18ca-11e7-8035-171a150918cb.png)

**Comment by smddzcy** [comment]
Looks good 👍 But it'd be better if you use "User" in the leftmost part and show the user's actions like the rest of us. You can make the change or not when you're available (in a separate enhancement issue, because this is very overdue). Also please don't forget to put it to the wiki.

**Comment by OnurOrhan** [comment]
![content creation sequence 5](https://cloud.githubusercontent.com/assets/25687182/24632144/c01befda-18cb-11e7-846d-8e9cc4321de3.png)

I couldn't put "User" on the left since the sequence doesn't start with the user. But I changed the style and I'm putting it now on the diagram page
