### ISSUE TITLE
Creating search an item sequence diagram

### ISSUE THREAD

**Issue by mehmetcalim** [bounswe/bounswe2017group3#45]
## About
Create a search an item sequence diagram by using Use Case 5.

**Comment by mehmetcalim** [comment]
Draft of search an item sequence diagram:

![searchanitem](https://cloud.githubusercontent.com/assets/25671417/23879658/21eb221a-0857-11e7-951b-c23511506920.png)

**Comment by smddzcy** [comment]
@mehmetcalim Can you please update the sequence diagram according to our new class diagram? You can take a look at https://cloud.githubusercontent.com/assets/25683353/24070485/14228164-0bc7-11e7-9b9f-bb9ac03701d8.png or https://cloud.githubusercontent.com/assets/13895224/23899636/a11a76d2-08be-11e7-9ff3-1ee672a45817.png for examples.

**Comment by gokceuludogan** [comment]
@mehmetcalim Could you edit this diagram as soon as possible to have enough time to review it?

**Comment by mehmetcalim** [comment]
![sequence_search](https://cloud.githubusercontent.com/assets/25671417/24122624/311d413c-0dc5-11e7-908b-71d94fdcf139.JPG)

**Comment by smddzcy** [comment]
@mehmetcalim This looks very good. One tiny thing: Methods in our search class are not static, so you probably should change `Search` to `search: Search` to show that's an _instance_ of the class.

**Comment by mehmetcalim** [comment]
@smddzcy I changed "Search" to "search: Search" and I will upload it to Sequence Diagrams page. Here its last version:

![sequence-search](https://cloud.githubusercontent.com/assets/25671417/24123873/069872ce-0dca-11e7-930f-088edf696101.png)

**Comment by smddzcy** [comment]
@mehmetcalim I think it looks good, thanks 👍 You can close the issue when you upload.

**Comment by smddzcy** [comment]
I think you forgot to close the issue. I saw the diagram is in our wiki 👌 Closing.
