### ISSUE TITLE
Create a sequence diagram for Use Case 8: Change the Privacy Settings

### ISSUE THREAD

**Issue by MertKalaylioglu** [bounswe/bounswe2017group3#46]
Create a sequence diagram for Use Case 8 (Change the Privacy Settings).

**Comment by MertKalaylioglu** [comment]
First draft for sequence diagram of "Use Case 8" is here.

![change group privacy settings](https://cloud.githubusercontent.com/assets/25799137/23879227/d3f6dfda-085c-11e7-80d1-ef4399fa780a.png)

**Comment by smddzcy** [comment]
Let's put all the drafts to wiki and sleep now 😴  (But we should improve these this week 😅 )

**Comment by MertKalaylioglu** [comment]
Sequence diagram of "Changing User Privacy Settings" is here.

![change user privacy settings](https://cloud.githubusercontent.com/assets/25799137/23880545/5c7d8202-0865-11e7-90cf-8aed2b2dd1c1.png)

**Comment by smddzcy** [comment]
@MertKalaylioglu I'm making this `in progress` since everything is changed 😄  Please take a look the service classes and my sequence diagram for an example.

**Comment by gokceuludogan** [comment]
@MertKalaylioglu Could you edit the diagram as soon as possible according to changes since we can have a enough time to review it?

**Comment by MertKalaylioglu** [comment]
Second draft for sequence diagram of "Use Case 8" is here.

![change group privacy settings - 2](https://cloud.githubusercontent.com/assets/25799137/24082390/e9f50e74-0cd5-11e7-88e7-2a7cfbf10f33.png)

**Comment by smddzcy** [comment]
@MertKalaylioglu Shared settings of activities (`Post`, `Group` or `Event` is called an `Activity` in our class diagram) like setting privacy, adding tag etc. are in `ActivityService`. Please take a look at the `Activity` interface 😄

**Comment by MertKalaylioglu** [comment]
Third draft for sequence diagram of "Use Case 8" is here.

![change group privacy settings - 2 1](https://cloud.githubusercontent.com/assets/25799137/24085764/b644dad6-0d12-11e7-9c7f-9a436bfdfe13.png)

**Comment by MertKalaylioglu** [comment]
Final draft for sequence diagram of "Use Case 8" is here.

Changing Group Privacy Setting
![change group privacy settings](https://cloud.githubusercontent.com/assets/25799137/24123221/b5d89656-0dcf-11e7-82b8-7fe4e7c786b9.png)

Changing User Privacy Setting
![change user privacy setting](https://cloud.githubusercontent.com/assets/25799137/24123295/f70c68d2-0dcf-11e7-9754-9f106ec767a9.png)

**Comment by smddzcy** [comment]
@MertKalaylioglu Looks very good, thanks 👌 Closing.
