### ISSUE TITLE
Sequence Diagram for Annotation

### ISSUE THREAD

**Issue by ugurcanarikan** [bounswe/bounswe2017group3#48]
## About

* **Related Issues:** #30

My task is to create a sequence diagram for adding annotations.

## To-do

- [x] Create the sequence diagram for adding annotations.

**Comment by ugurcanarikan** [comment]
![s](https://www.websequencediagrams.com/cgi-bin/cdraw?lz=dGl0bGUgQW5ub3RhdGlvbiBTZXF1ZW5jZQoKVXNlci0-K1VzZXIgSW50ZXJmYWNlOiBjbGljayBvbiB0aGUgYWRkIGEAMwpidXR0b24ANQUAKQotPlVzZXI6IHVzZXIgaXMgZGlyZWN0ZWQgdG8AMBBwYWdlAHEHAGcQADkFYWRkcwBlCwBYEStTeXN0ZW06IGFkZACBSgooAIEYCjoAgWALKQoAKAYtPi0AgVQQU3VjY2VzcwCBMhcAgiMLaXMgYWRkZWQKIAoKCgoKCgo&s=default)
I assumed add annotation button will appear only for image and text so that the system won't have to check if the post can be annotated.Also addAnnotation() method should be added to the class diagram.

**Comment by gokceuludogan** [comment]
We don't have a class named User Interface. Please check the new version of our class diagram and the sequence diagrams edited based on this one. We are allowed to use only the classes in the diagram and Database for convenience. Could you edit the diagram according to changes? @ugurcanarikan

**Comment by ugurcanarikan** [comment]
![](https://www.websequencediagrams.com/cgi-bin/cdraw?lz=dGl0bGUgQW5ub3RhdGlvbiBTZXF1ZW5jZQoKVXNlci0-VXNlcjogY2xpY2sgb24gdGhlIGFkZCBhACgKYnV0dG9uACgHK1Bvc3QgU2VydmljZTogYWRkAFIKKHVzZXJJRDpVVUlELHZhbHVlczpNYXA8U3RyaW5nLE9iamVjdD4pCgA3DC0-AEMOY2hlY2sgaWYgaW5wdXQgc3ludGF4IGlzIHZhbGlkCmFsdAAEBgAaBgogICAgAEINLT4AgWIKOjw8Y3JlYXRlPj4AFxI-K0RhdGFiYXNlOiAAIAYAgWgMcmVjb3JkAFoFAB8ILS0-LQCBbw5zdWNjZXNzAHEUAIJQBgAaByAKZWxzZSBpbgCBGx8tAIMGBgAbDSBlcnJvcgCBYwUKCgoKCgoKCgo&s=default)

@gokceuludogan I have modified it according to new class diagram
