### ISSUE TITLE
Add service classes to class diagram

### ISSUE THREAD

**Issue by smddzcy** [bounswe/bounswe2017group3#49]
## About

* **Related Issues:** #40 

We saw that we don't have service classes to interact with our actual classes in our API, so we should create those.

**Comment by smddzcy** [comment]
Here is the refactored class diagram with added service classes:
![class diagram](https://cloud.githubusercontent.com/assets/13895224/23897858/6eae1ec6-08b7-11e7-8a71-95bbc75ffb92.png)

**Comment by smddzcy** [comment]
@bounswe/bounswe2017group3 Can you all please check (and review in the process) the new class diagram? We should design our sequence diagrams by using the new service classes 😄

Also; I've asked the instructor about the database operations. She said we shouldn't create a class for it (obviously), but we should show the database in our sequence diagrams with high-level descriptions like: "query the user", "create a group with props" etc.

**Comment by ugurcanarikan** [comment]
Can you also add a method about adding an annotation?

**Comment by smddzcy** [comment]
@ugurcanarikan I've added an `addAnnotation` method to `PostService`. Is this enough?

Here is the new diagram:
![class diagram](https://cloud.githubusercontent.com/assets/13895224/24079268/6d4c9200-0c8c-11e7-8137-a119234c4a81.png)

**Comment by gokceuludogan** [comment]
@smddzcy Since the annotations can be added anywhere in a page, I think we should generalize this method instead of adding it only to PostService.

**Comment by smddzcy** [comment]
@gokceuludogan Changed the annotation. Check this out:
![class diagram - page 1](https://cloud.githubusercontent.com/assets/13895224/24082336/a7005be0-0ccc-11e7-953f-f74b5cdba223.png)

**Comment by smddzcy** [comment]
Thanks for the reviews. Since no one has any problem anymore, I think that our class diagram is enough for our use cases. Closing 🚀
