### ISSUE TITLE
Upload the project plan .pod file to our Google Drive folder

### ISSUE THREAD

**Issue by smddzcy** [bounswe/bounswe2017group3#57]
## About

* **Other Related Links:** https://github.com/bounswe/bounswe2017group3/wiki/Meeting-7-24.03.2017

We should upload our project plan file to Google Drive for easy access.

**Comment by MertKalaylioglu** [comment]
.mpp file (MS Project file) is uploaded to Slack. Anybody can download the project plan file from Slack.
