### ISSUE TITLE
Fix typos and language problems in the project plan

### ISSUE THREAD

**Issue by smddzcy** [bounswe/bounswe2017group3#58]
## About

* **Related Issues:** https://github.com/bounswe/bounswe2017group3/issues/57
* **Other Related Links:** https://github.com/bounswe/bounswe2017group3/wiki/Meeting-7-24.03.2017

Our project plan contains small typos and some language problems. We should fix those.

**Comment by smddzcy** [comment]
I'll finish it as soon as I get the `.pod` file 😄

**Comment by esra-aydemir** [comment]
It is on slack and github now anyone can review for minor errors. Otherwise this version will be accepted as final version.

**Comment by gokceuludogan** [comment]
I think we have to add another milestone for this semester it might be after testing and analysis parts are completed. Moreover, the slack times are still missing.

**Comment by smddzcy** [comment]
We should definitely add the slack times ASAP. Who can do this? @bounswe/bounswe2017group3

**Comment by smddzcy** [comment]
This looks pretty done. Closing 👍
