### ISSUE TITLE
Enhancing the Project Plan

### ISSUE THREAD

**Issue by MertKalaylioglu** [bounswe/bounswe2017group3#59]
There are some misunderstandings in Project Plan.

What is the difference between Class Diagram in Behavioral Modeling and System Classes in Structural Modeling?

What is the difference between Activity Diagrams and Action Diagrams?

Funding and analysis parts are unclear and have no assignees (resources).

**Comment by esra-aydemir** [comment]
[projectPlan2.pdf](https://github.com/bounswe/bounswe2017group3/files/906186/projectPlan2.pdf)
[projectPlan.pdf](https://github.com/bounswe/bounswe2017group3/files/906185/projectPlan.pdf)
