### ISSUE TITLE
Choosing the framework to use for Java API

### ISSUE THREAD

**Issue by smddzcy** [bounswe/bounswe2017group3#62]
## About

We should choose a framework to speed up our API development process in Java.

**Comment by smddzcy** [comment]
A very easy and tiny REST API framework for Java: http://sparkjava.com/

Here is the "Hello, World!" code:
```
import static spark.Spark.*;

public class HelloWorld {
    public static void main(String[] args) {
        get("/hello", (req, res) -> "Hello World");
    }
}
```

Also, we can take a look at these ones too: http://www.gajotres.net/best-available-java-restful-micro-frameworks/

**Comment by gokceuludogan** [comment]
Spark seems very good for creating an API!

**Comment by smddzcy** [comment]
The only problem is it doesn't parse the POST body params for us 😄 It looks very simple and elegant, but we have to implement (or find) a form-data parser to use it.

**Comment by gokceuludogan** [comment]
@smddzcy Since we have decided to use python in creating API, we should edit or close this issue.

**Comment by smddzcy** [comment]
I think Python can be hard since noone knows it 😄 Should we make a poll to choose the language?

**Comment by gokceuludogan** [comment]
@smddzcy I thought that the decision has been made in the meeting as far as I understand from the meeting notes. However,  it's better to make a decision after the poll.

**Comment by smddzcy** [comment]
@bounswe/bounswe2017group3 Now, Java is selected and as far as I could understand Spring framework is OK for everyone. If it is, then we should close this issue and start documenting our API 😄

**Comment by esra-aydemir** [comment]
Spring is the framework we will use.
