### ISSUE TITLE
Complete sequence diagrams

### ISSUE THREAD

**Issue by esra-aydemir** [bounswe/bounswe2017group3#63]
## About

* **Related Issues:** #52 

Currently there are 12 [Use Cases](https://github.com/bounswe/bounswe2017group3/wiki/Use-Cases) but 9 [Sequence Diagrams](https://github.com/bounswe/bounswe2017group3/wiki/Sequence-Diagrams). We shall complete the missing sequence diagrams and review the existing ones.

**Comment by gokceuludogan** [comment]
I think it is not obligatory to have a sequence diagram for each use case. Additionally, there is a mistake in the use case 12. Moderators are allowed to ban a user from their group/event, not from the site, removing from the site is the responsibility of the admin. Could you edit that use case please? @mtoygar

**Comment by gokceuludogan** [comment]
Ok I have solves the conflict in the use case 12. Since it is not obligatory to have a sequence diagram for each use case and also the remaining ones are not crucial, I think we can close this issue. Could you close this if you agree with me?  @esra-aydemir
