### ISSUE TITLE
Improving our Kanban board 

### ISSUE THREAD

**Issue by smddzcy** [bounswe/bounswe2017group3#65]
## About

* **Other Related Links:** Link to our board: https://github.com/bounswe/bounswe2017group3/projects/1?fullscreen=true

We should add the missing issues to our Kanban board and improve the columns (changing some names and adding missing columns like `QA / Review`).

## Visuals

Finalized board:
![screen shot 2017-04-09 at 14 56 16](https://cloud.githubusercontent.com/assets/13895224/24837077/b691e790-1d34-11e7-85da-38a4e83b5332.png)

## To-do

- [x] Add missing issues to the board, and move some of them to more appropriate columns.
- [x] Add a `QA / Review` column.

**Comment by smddzcy** [comment]
I've added the picture of the finalized board.

**Comment by gokceuludogan** [comment]
@smddzcy Good work!

**Comment by smddzcy** [comment]
@gokceuludogan Thanks 🍾  Closing this one.
