### ISSUE TITLE
Create milestone 2 in GitHub

### ISSUE THREAD

**Issue by smddzcy** [bounswe/bounswe2017group3#66]
## About

* **Other Related Links:** Our project plan: https://github.com/bounswe/bounswe2017group3/wiki/Project-Plan

We should create the milestone 2 in GitHub and add the relevant issues to that.

**Comment by gokceuludogan** [comment]
I think we can add one after the testing and analysis parts are completed through the end of April or beginning of May.

**Comment by smddzcy** [comment]
It looks like someone already added a milestone 😄

**Comment by gokceuludogan** [comment]
We have added it on meeting but I think we should also add a page clarifying what the functionality and the deliverables of these milestones are.

**Comment by smddzcy** [comment]
@gokceuludogan We already have that, that's our project plan. Anyways, I'm closing this one, maybe we can continue on another issue if we want to enhance our milestone specs. 🤞
