### ISSUE TITLE
Create a test case for searching an item  

### ISSUE THREAD

**Issue by gokceuludogan** [bounswe/bounswe2017group3#86]
## About

* **Related Issues:** #85 
* **Other Related Links:** https://github.com/bounswe/bounswe2017group3/wiki/Use-Cases 

We should create test cases for our project and I am assigned to create a test for searching an item. 

## To-do

- [x] Create a test case for searching an item

**Comment by gokceuludogan** [comment]
@smddzcy could you review please ? :smile:

**Comment by smddzcy** [comment]
@gokceuludogan Everything looks good 👌
