### ISSUE TITLE
Create test cases for tagging an item.

### ISSUE THREAD

**Issue by mtoygar** [bounswe/bounswe2017group3#89]
## About

* **Related Issues:** #85
* **Other Related Links:** [Wiki Use Cases Page](https://github.com/bounswe/bounse2017group3/wiki/Use-Cases)

We should create test cases for our project, and I assigned myself to complete test cases for tagging an item

## To-do

- [ ] Create test cases for tagging an item.

**Comment by gokceuludogan** [comment]
@mtoygar Test cases look fine :+1:

**Comment by mtoygar** [comment]
I close this issue, thx :checkered_flag:
