### ISSUE TITLE
Create a test case for warning/banning a user

### ISSUE THREAD

**Issue by smddzcy** [bounswe/bounswe2017group3#93]
## About

* **Related Issues:** https://github.com/bounswe/bounswe2017group3/issues/85
* **Other Related Links:** Our mockups to better understand the test steps: https://github.com/bounswe/bounswe2017group3/wiki/Web-Mockups

I'll create a test case for warning and banning a user in a group.

**Comment by smddzcy** [comment]
Test case for warning a user:
https://github.com/bounswe/bounswe2017group3/wiki/Test-Cases#test-case-id-tc_7

Test case for banning a user:
https://github.com/bounswe/bounswe2017group3/wiki/Test-Cases#test-case-id-tc_8

@gokceuludogan Can you please review? 😄

**Comment by gokceuludogan** [comment]
@smddzcy Perfect :+1:

**Comment by smddzcy** [comment]
@gokceuludogan Thank you, closing 🚀
